extends Resource
class_name WeaponData

@export var id: StringName = &"basic_pistol"
@export var display_name: String = "Basic Pistol"
@export_multiline var description: String = "Reliable sidearm."
@export_enum("starter", "common", "rare", "epic", "legendary") var rarity: String = "common"
@export_enum("sidearm", "shotgun", "staff", "launcher", "laser", "melee", "core") var weapon_class: String = "sidearm"
@export_enum("close", "mid", "long", "all") var recommended_range: String = "mid"
@export var drop_weight: float = 1.0
@export var unlock_id: String = ""
@export var content_role: String = "baseline"
@export var damage: int = 1
@export var fire_rate: float = 6.0
@export var projectile_speed: float = 720.0
@export var projectile_range: float = 720.0
@export var projectile_count: int = 1
@export var spread_angle: float = 0.0
@export_enum("projectile", "radial", "melee", "charge", "deployable") var fire_mode: String = "projectile"
@export var energy_cost: int = 0
@export var magazine_size: int = 12
@export var reload_duration: float = 1.0
@export var knockback: float = 120.0
@export_range(0.0, 1.0, 0.01) var crit_chance: float = 0.05
@export var crit_multiplier: float = 2.0
@export var pierce_count: int = 0
@export var bounce_count: int = 0
@export var homing_turn_rate: float = 0.0
@export var homing_radius: float = 0.0
@export var chain_count: int = 0
@export var chain_radius: float = 0.0
@export_range(0.1, 2.0, 0.05) var chain_damage_multiplier: float = 0.65
@export var explosion_radius: float = 0.0
@export_enum("none", "burn", "slow") var status_effect: String = "none"
@export_range(0.0, 1.0, 0.01) var status_chance: float = 0.0
@export var status_duration: float = 0.0
@export var status_damage_per_tick: int = 0
@export var status_tick_interval: float = 1.0
@export_range(0.1, 1.0, 0.05) var status_slow_multiplier: float = 1.0
@export var blocks_projectiles: bool = false
@export var projectile_block_radius: float = 110.0
@export_range(1.0, 360.0, 1.0) var projectile_block_arc_degrees: float = 120.0
@export var projectile_block_damage: int = 0
@export var charge_duration: float = 0.0
@export var charge_damage_multiplier: float = 1.0
@export var charge_projectile_speed_multiplier: float = 1.0
@export var charge_projectile_count_bonus: int = 0
@export_enum("field", "mine", "sentry") var deployable_behavior: String = "field"
@export var deployable_duration: float = 0.0
@export var deployable_radius: float = 0.0
@export var deployable_tick_interval: float = 0.5
@export var deployable_arming_time: float = 0.0
@export var deployable_damage_multiplier: float = 1.0
@export var aim_assist_priority: float = 1.0
@export var icon_key: String = ""
@export var fire_sfx_key: String = ""
@export var projectile_vfx_key: String = ""
@export var tags: PackedStringArray = []
