extends Node

signal player_fired(weapon_data: Resource, origin: Vector2, direction: Vector2)
signal projectile_spawned(projectile: Node)
signal projectile_hit(projectile: Node, target: Node, damage: int)
signal projectile_critical_hit(projectile: Node, target: Node, damage: int)
signal enemy_damaged(enemy: Node, damage: int)
signal enemy_died(enemy: Node)
signal enemy_spawned(enemy: Node)
signal player_damaged(amount: int, current_hp: int)
signal player_healed(amount: int, current_hp: int)
signal player_shield_gained(amount: int, current_shield: int)
signal player_shield_absorbed(amount: int, current_shield: int)
signal player_energy_changed(current_energy: int, max_energy: int)
signal player_died()
signal gold_changed(current_gold: int)
signal room_state_changed(room: Node, state_name: String)
signal room_started(room: Node)
signal room_cleared(room: Node)
signal reward_spawned(reward: Node)
signal reward_collected(reward: Node, collector: Node)
signal dungeon_generated(room_records: Array)
signal dungeon_updated(room_records: Array, current_room_id: String)
signal relic_choice_requested(relic_choices: Array, source_pickup: Node, collector: Node)
signal relic_choice_selected(index: int)
signal relic_collected(relic_data: Resource, stack_count: int)
signal relics_changed(relic_summaries: Array)
signal boss_health_changed(boss: Node, current_hp: int, max_hp: int)
signal boss_phase_changed(boss: Node, phase: int)
signal boss_died(boss: Node)
signal run_completed()
signal shop_item_purchased(shop_item: Node, buyer: Node, price: int, item_type: String)
signal shop_purchase_failed(shop_item: Node, buyer: Node, price: int, reason: String)
signal chest_opened(chest: Node, opener: Node, chest_type: String)
